apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: nginx.ingress.kubernetes.io/controller
###################################
# INGRESS
###################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abcall-web-ingress
  labels:
    name:  abcall-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: abcall-web.lab-cloud-development.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: abcall-web-service
            port:
              number: 80
