apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  worker-processes: "2"
  http-snippet: |
    server {
      listen 80;
      server_name lab-cloud-development.xyz;
      return 301 https://$host$request_uri;
    }
