apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  worker-processes: "2"
  http-snippet: |
    server {
      listen 80;
      server_name lab-cloud-development.xyz;
      root /usr/share/nginx/html;
      index index.html;


      location / {
          try_files $uri $uri/ /index.html;
      }


      location ~* \.(?:css|js|json|map|jpg|png|gif|svg|ico|woff|woff2|ttf|eot)$ {
          expires 1y;
          add_header Cache-Control "public, max-age=31536000, immutable";
      }


      error_page 404 /index.html;
    }
